### ISSUE TITLE
Anyway to do test faster?

### ISSUE THREAD

**Issue by ant1pink** [Abhijit-2592/Keras_object_detection#7]
Hi there,

Is there any methods that can make the test process faster? 
Also Keras has VGG and resnet in their application now, maybe we can use that to simplify this code.

Thanks,

Ray

**Comment by Abhijit-2592** [comment]
You cannot directly call the VGG, Resnet from keras.applications because the FRCNN requires the architecture to be split into before RPN and after RPN layers. See my comment in #6 . I don't think it is directly possible to increase the speed of the inference. You can however try parallel processing using multi GPUs if you want.

**Comment by ant1pink** [comment]
Okay, thank you very much.

**Comment by ant1pink** [comment]
Hi Abhijit,

Have you got the problem that the size of the object/logo you going to detection is too small to detect? 
Does it help if I create more training samples with small size?

Thanks,

Ray
